### ISSUE TITLE
Is rocketmq package in pypi an offcial version?

### ISSUE THREAD

**Issue by 2h4dl** [apache/rocketmq-client-python#46]
I found a rocketmq python client in <https://pypi.org/project/rocketmq/>.

Is that an official version from you guys?

**Comment by ifplusor** [comment]
It is not official version. @messense commit it, and it's repo is https://github.com/messense/rocketmq-python

**Comment by messense** [comment]
I wrote `rocketmq-python` because in my opinion `rocketmq-client-python` is way too hard to use. It requires developers compiling `rocketmq-client-cpp` by themselves which is complicated, and its API is really lower level and IMHO ugly.

`rocketmq-python` is  a high level wrapper of `rocketmq-client-cpp`. It's easy to install with `pip` thank to precompiled `manylinux1` binary wheels. And its API is built with **pythonic** and easy to use in mind.

**Comment by 2h4dl** [comment]
Hi @ifplusor, I compiled `branch python3` with cmake, have many problems, like this issue<https://github.com/apache/rocketmq-client-python/issues/34>.
And Thanks @messense provide an easily use client.

**Comment by ifplusor** [comment]
@2h4dl We can discuss it in wechat or dingding.

**Comment by 2h4dl** [comment]
@ifplusor lcgxwgp, my dingding accout.

**Comment by duhenglucky** [comment]
@messense The current API is really low-level, and it doesn't do much encapsulation. Would you like to provide a pythonic client based on the current low-level API? Besides, https://github.com/messense/rocketmq-python is really excellent work.

**Comment by messense** [comment]
@duhengforever We can discuss it in Dingding, my account is `generics`
