### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by sicklife** [apache/rocketmq-client-python#96]
**BUG REPORT**

1. Please describe the issue you observed:

here is my code
```python
import uuid

from rocketmq.client import Producer, Message

producer = Producer(str(uuid.uuid1()), max_message_size=1000000)

producer.set_name_server_address(".....")

producer.start()

for _ in range(1000000):
    msg = Message("test_topic")

    msg.set_body("test_mg ")

    msg.set_tags("*")

    producer.send_sync(msg)

producer.shutdown()
```

- What did you expect to see?
progress memory is steady.

- What did you see instead?
the res memory of this process is continues to grow. Infact the memory will continue grow until eat up all memory avialable.

2. Please tell us about your environment:

 - What is your OS?
centos7
 - What is your client version?
lastest from pip

 - What is your RocketMQ version?
4.4.0

3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**Comment by qykong** [comment]
We recently encountered a bug while utilizing the Python SDK, installed via pip. To assist others who might face the same issue, it would be highly beneficial if this fix could be made available on pip. Alternatively, mentioning it in the Readme would also be helpful, as it could save time for users who might otherwise spend it identifying and understanding this specific problem.
